/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author oshada kavintha
 */
public class DeleteEXP extends javax.swing.JDialog {

    /**
     * Creates new form DeleteEXP
     */
    public DeleteEXP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadExpireProduct();
    }
    
    Home home;
    public DeleteEXP(Home home) {
        initComponents();
        this.home = home;
        loadExpireProduct();
    }
    
    public void loadExpireProduct(){
        try {
            
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            String dNow = sdf1.format(new Date());
            LocalDate date = LocalDate.parse(dNow);
    
            ResultSet rse = MySQL.search("SELECT `stock`.`id`,`stock`.`quantity`,`stock`.`exd`,`product`.`name` AS `product` FROM `stock` INNER JOIN `product` ON `stock`.`product_id`=`product`.`id` WHERE `stock`.`exd`<='"+dNow+"' AND `stock`.`quantity` > '0' ORDER BY `stock`.`exd` DESC");
            
            DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            
            while(rse.next()){
                Vector v = new Vector();
                v.add(rse.getString("id"));
                v.add(rse.getString("product"));
                v.add(rse.getString("quantity"));
                v.add(rse.getString("exd"));
                dtm.addRow(v);
            }
            jTable1.setModel(dtm);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove Quantity of Expire Product");
        setAlwaysOnTop(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock ID", "Product Name", "Quantity", "EXP date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Remove All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int r = jTable1.getSelectedRow();

            if(r==-1){
                JOptionPane.showMessageDialog(this, "Pleace select a Item", "warning", JOptionPane.WARNING_MESSAGE);
            }else{
                int option = JOptionPane.showConfirmDialog(this, "Do you want to remove quantity of selected product?", "confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if(option == JOptionPane.YES_OPTION){
                    
                    MySQL.iud("UPDATE `stock` SET `quantity`='0' WHERE `id`='"+jTable1.getValueAt(r, 0).toString()+"'");
                    
                    JOptionPane.showMessageDialog(this, "Stock quantity removed from selected.", "success", JOptionPane.INFORMATION_MESSAGE);
                    loadExpireProduct();
                    
                    home.jDesktopPane3.removeAll();
                    home.jDesktopPane3.revalidate();
                    home.jDesktopPane3.repaint();
                    home.viewExpiredProduct();
                }

            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                int rc = jTable1.getRowCount();
                if(rc!=0){
                int option = JOptionPane.showConfirmDialog(this, "Do you want to remove quantity of all expire product?", "confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if(option == JOptionPane.YES_OPTION){
                    
                    for(int i=0; i<rc; i++){
                         MySQL.iud("UPDATE `stock` SET `quantity`='0' WHERE `id`='"+jTable1.getValueAt(i, 0).toString()+"'");
                    }
                   
                    JOptionPane.showMessageDialog(this, "Stock quantity removed from expire products.", "success", JOptionPane.INFORMATION_MESSAGE);
                    loadExpireProduct();
                    
                    home.jDesktopPane3.removeAll();
                    home.jDesktopPane3.revalidate();
                    home.jDesktopPane3.repaint();
                    home.viewExpiredProduct();
                }
                }else{
                    JOptionPane.showMessageDialog(this, "There is no expire product for remove.", "information", JOptionPane.INFORMATION_MESSAGE);
                }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEXP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEXP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEXP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEXP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeleteEXP dialog = new DeleteEXP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
